datagrabber:
  kind: OasisVBMTestingDatagrabber
markers:
- atlas: Schaefer1000x7
  kind: ParcelAggregation
  method: mean
  name: Schaefer1000x7_Mean
storage:
  kind: SQLiteFeatureStorage
  uri: /Users/fraimondo/dev/tbox/junifer/scratch/db/test.db
workdir: /tmp
