name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check for sudo
      shell: bash
      run: |
        if type sudo >/dev/null 2>&1; then SUDO="sudo"; else SUDO=""; fi
        echo "SUDO=$SUDO" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        $SUDO bash -c "$(curl -fsSL http://neuro.debian.net/_files/neurodebian-travis.sh)"
        $SUDO apt-get update -qq
        $SUDO apt-get install git-annex-standalone
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install tox tox-gh-actions
    - name: Configure git for datalad
      run: |
        git config --global user.email "runner@github.com"
        git config --global user.name "GITHUB CI Runner"
    - name: Test with tox
      run: |
        tox
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@master
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      if: success() && matrix.python-version == 3.9
